import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './matrix-overlay.css';
import './clients-tab.css';
import './home-cleanup.css';
import './clients-home-entry.css';
import './report-sources.css';
import './client-detail-no-scroll.css';
import './client-analysis-progress.css';
import './client-field-copy.css';
import './client-review-mode.css';
import './client-divergence-filter.css';
import './client-report-search.css';
import './client-session-history.css';
import './client-capabilities.css';
import './iguasport-client.css';
import './xcmg-client.css';
import './kemin-client.css';
import './clients-tab';
import './clients-home-entry';
import './xcmg-report-sources';
import './xcmg-cnpj-preview-exact';
import './report-preview-loader';
import './client-analysis-progress';
import './client-field-copy';
import './client-review-mode';
import './client-divergence-filter';
import './client-report-search';
import './client-session-history';
import './client-capabilities';
import './iguasport-client';
import './xcmg-client';
import './kemin-report-sources';
import './kemin-client';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode><App /></React.StrictMode>
);
